version: '3.6'

services: 
    mysqldb:
      container_name: pj_mysqldb
      image: mysql:8.0
      restart: always
      env_file: ./.env
      environment:
          - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - MYSQL_DATABASE=$MYSQLDB_DATABASE
      ports:
          - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      networks:
          - pj
        
    pj_app:
      container_name: pj_app
      depends_on:
        - mysqldb
      build: ./
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      environment:
        - DB_NAME=$MYSQLDB_DATABASE
        - DB_HOST=$MYSQLDB_HOST
        - DB_USERNAME=$MYSQLDB_USER
        - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - DB_PORT=$MYSQLDB_DOCKER_PORT
        - DB_DIALECT=mysql
      stdin_open: true
      tty: true
      networks:
        - pj

networks:
  pj:
    name: pj